micronaut:
  application:
    name: keyManagerRest
  server:
   port: ${SERVER_PORT:8077}

# Mudança para comunicar com o arquivo grpc do docker
grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: '${KEY_MANAGER_HOST:host.docker.internal}:${KEY_MANAGER_PORT:50051}'

# Local
#      address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}'

##
# Jackson configuration
# https://github.com/micronaut-projects/micronaut-core/issues/240
# https://geowarin.com/correctly-handle-jsr-310-java-8-dates-with-jackson/
# https://www.baeldung.com/jackson-serialize-dates
# Configuração para serializar a data
##
jackson:
  serialization:
    writeDatesAsTimestamps: false